version: '3.6'
services:

  arm-img-builder:
    build: .  #uncomment for building 
#    image: pttrr/arm-img-builder:latest 
  #  image: pttrr/arm-img-builder:native #uncomment for native compiling
    privileged: true
    container_name: arm-img-builder
    tty: true
    restart: always
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /dev:/dev
      - ./:/images
