version: '3.6'
services:
  arm-img-builder:
#    build: .  #uncomment for building
    image: pttrr/arm-img-builder:cross
    privileged: true
    container_name: arm-img-builder
    hostname: arm-img-builder
    network_mode: bridge
    tmpfs:
    - /tmp
    - /run
    - /run/lock
    volumes:
    - /dev:/dev
    - /sys/fs/cgroup:/sys/fs/cgroup:ro
    - ./:/build
