version: '3.6'
services:

  arm-img-builder:
    build: .  #uncomment for building
#    image: pttrr/arm-img-builder:devel # for crosscompiling
#    image: pttrr/arm-img-builder:native # if building on a arm64 with docker
    privileged: true
    cap_add:
      - MKNOD
      - SYS_PTRACE
      - SYS_ADMIN
    container_name: arm-img-builder
    tty: true
    volumes:
      - ./:/images
      - /dev:/dev
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
